#!/usr/bin/env python3
"""Generate README.md and docs/timeline_data.json from data/*.json."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
AREA_ORDER = ["Image", "Video", "Text", "Audio", "Multimodal"]
GENERATED_NOTICE = "<!-- This section is generated by scripts/generate_readme.py. Do not edit by hand. -->"


def load_json(path: Path) -> list[dict[str, Any]]:
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a JSON list")
    return data


def write_json(path: Path, data: list[dict[str, Any]]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def clean_cell(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\n", " ").replace("|", "\\|").strip()
    return text or "-"


def md_link(label: str, url: str) -> str:
    label = clean_cell(label)
    return f"[{label}]({url})" if url else label


def normalize_venue(venue: str) -> str:
    return "arXiv" if venue.lower() == "arxiv" else venue


def sort_papers(papers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    area_rank = {area: i for i, area in enumerate(AREA_ORDER)}
    return sorted(
        papers,
        key=lambda p: (
            -int(p["year"]),
            -int(p["month"]),
            area_rank.get(p["area"], 99),
            str(p["venue"]).lower(),
            str(p["title"]).lower(),
        ),
    )


def render_table(headers: list[str], rows: list[list[Any]]) -> str:
    if not rows:
        return "_No entries yet._\n"
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    out.extend("| " + " | ".join(clean_cell(cell) for cell in row) + " |" for row in rows)
    return "\n".join(out) + "\n"


def render_stats(papers: list[dict[str, Any]], datasets: list[dict[str, Any]]) -> str:
    years = [int(p["year"]) for p in papers]
    area_counts = Counter(p["area"] for p in papers)
    venue_counts = Counter(normalize_venue(str(p["venue"])) for p in papers)

    stats_rows: list[list[Any]] = [
        ["Total Papers", len(papers)],
        ["Datasets", len(datasets)],
        ["Timespan", f"{min(years)} - {max(years)}" if years else "-"],
    ]
    stats_rows.extend([f"{area} Detection", area_counts.get(area, 0)] for area in AREA_ORDER)

    venue_rows = [[venue, count] for venue, count in venue_counts.most_common(12)]
    return (
        f"{GENERATED_NOTICE}\n\n"
        + render_table(["Category", "Count"], stats_rows)
        + "\n### By Venue\n\n"
        + render_table(["Venue", "Papers"], venue_rows)
    )


def render_datasets(datasets: list[dict[str, Any]]) -> str:
    rows = []
    for item in sorted(datasets, key=lambda d: (int(d["year"]), d["name"].lower())):
        rows.append(
            [
                item["year"],
                md_link(item["name"], item.get("url", "")),
                item.get("real_count", "-"),
                item.get("fake_count", "-"),
                item.get("scale", "-"),
                item.get("real_sources", "-"),
                item.get("generation_methods", "-"),
            ]
        )
    return f"{GENERATED_NOTICE}\n\n" + render_table(
        ["Year", "Dataset", "Real", "Fake", "Scale", "Real Sources", "Generation Methods"],
        rows,
    )


def render_papers(papers: list[dict[str, Any]]) -> str:
    rows = []
    for paper in sort_papers(papers):
        links = []
        if paper.get("paper_url"):
            links.append(md_link("Paper", paper["paper_url"]))
        if paper.get("code_url"):
            links.append(md_link("Code", paper["code_url"]))
        if paper.get("project_url"):
            links.append(md_link("Project", paper["project_url"]))
        methods = ", ".join(paper.get("methods", [])) or "-"
        tags = ", ".join(paper.get("tags", [])) or "-"
        rows.append(
            [
                paper["year"],
                paper["month"],
                paper["area"],
                normalize_venue(paper["venue"]),
                md_link(paper["title"], paper.get("paper_url", "")),
                " / ".join(links) if links else "-",
                methods,
                tags,
            ]
        )
    return f"{GENERATED_NOTICE}\n\n" + render_table(
        ["Year", "Month", "Area", "Venue", "Title", "Links", "Methods", "Tags"],
        rows,
    )


def render_tools(tools: list[dict[str, Any]]) -> str:
    lines = [GENERATED_NOTICE, ""]
    categories = sorted({tool["category"] for tool in tools})
    for category in categories:
        lines.append(f"### {category}")
        lines.append("")
        rows = []
        for tool in sorted([t for t in tools if t["category"] == category], key=lambda t: t["name"].lower()):
            rows.append(
                [
                    md_link(tool["name"], tool.get("url", "")),
                    tool.get("language", "-"),
                    tool.get("platform", "-"),
                    tool.get("description", "-"),
                ]
            )
        lines.append(render_table(["Tool", "Language", "Platform", "Description"], rows).rstrip())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def make_short_title(title: str) -> str:
    text = re.sub(r"<[^>]+>", "", html.unescape(title)).strip()
    first_part = text.split(":")[0].strip()
    if 0 < len(first_part) <= 24:
        return first_part
    words = first_part.split()
    return " ".join(words[:2]) if len(words) > 1 else first_part[:24]


def build_timeline_data(papers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    output = []
    for paper in sort_papers(papers):
        area = paper["area"]
        output.append(
            {
                "id": paper["id"],
                "name": paper["title"],
                "short": make_short_title(paper["title"]),
                "year": paper["year"],
                "month": paper["month"],
                "area": area,
                "category": f"{area} Detection",
                "venue": paper["venue"],
                "conference": paper["venue"],
                "paper_url": paper.get("paper_url", ""),
                "arxiv": paper.get("arxiv_id", ""),
                "code_url": paper.get("code_url", ""),
                "project_url": paper.get("project_url", ""),
                "code": paper.get("code_url", "") or paper.get("project_url", ""),
                "quarter": f"Q{((int(paper['month']) - 1) // 3) + 1}",
                "methods": paper.get("methods", []),
                "tags": paper.get("tags", []),
                "landmark": bool(paper.get("is_landmark", False)),
                "notes": paper.get("notes", ""),
            }
        )
    return output


def render_readme(papers: list[dict[str, Any]], datasets: list[dict[str, Any]], tools: list[dict[str, Any]]) -> str:
    return f"""# Awesome-AIGC-Detection

> 本仓库由 OpenClaw (🦞) 和人类共同维护

<div align="center">

[![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)
[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](http://makeapullrequest.com)
[![GitHub stars](https://img.shields.io/github/stars/MuskAI/Awesome-AIGC-Detection?style=flat-square)](https://github.com/MuskAI/Awesome-AIGC-Detection/stargazers)
[![GitHub forks](https://img.shields.io/github/forks/MuskAI/Awesome-AIGC-Detection?style=flat-square)](https://github.com/MuskAI/Awesome-AIGC-Detection/network)
[![License](https://img.shields.io/github/license/MuskAI/Awesome-AIGC-Detection?style=flat-square)](LICENSE)

</div>

---

![](ai-detector-social.jpg)

> 🔍 A comprehensive collection of papers, datasets, and tools for AI-Generated Content (AIGC) detection research.

This repository tracks research on detecting AI-generated content across image, video, text, audio, and multimodal settings. Paper, dataset, tool, README, and timeline metadata are generated from structured files under `data/`.

Recent image/video entries are cross-referenced with [ant-research/Awesome-AIGC-Image-Video-Detection](https://github.com/ant-research/Awesome-AIGC-Image-Video-Detection).

**[🕐 Interactive Timeline](https://muskai.github.io/Awesome-AIGC-Detection/timeline.html)** · **[Local HTML](./docs/timeline.html)** · **[📊 View as Table](#-papers)**

---

## 🚀 Quick Start

```bash
git clone https://github.com/MuskAI/Awesome-AIGC-Detection.git
cd Awesome-AIGC-Detection

python3 scripts/validate_data.py
python3 scripts/generate_readme.py --check
```

---

## 📊 Statistics

<!-- BEGIN GENERATED STATS -->
{render_stats(papers, datasets).rstrip()}
<!-- END GENERATED STATS -->

---

## 📋 Table of Contents

- [Datasets](#-datasets)
- [Papers](#-papers)
- [Tools](#-tools)
- [Contributing](#-contributing)

## 📚 Datasets

<!-- BEGIN GENERATED DATASETS -->
{render_datasets(datasets).rstrip()}
<!-- END GENERATED DATASETS -->

## 📝 Papers

<!-- BEGIN GENERATED PAPERS -->
{render_papers(papers).rstrip()}
<!-- END GENERATED PAPERS -->

## 🔧 Tools

<!-- BEGIN GENERATED TOOLS -->
{render_tools(tools).rstrip()}
<!-- END GENERATED TOOLS -->

## 🏙️ Others

- Paper backlog: [PAPERS_TO_ADD.md](./PAPERS_TO_ADD.md)
- Timeline source: [docs/timeline_data.json](./docs/timeline_data.json), generated from [data/papers.json](./data/papers.json)

---

## 🤝 Contributing

Contributions are welcome. To add or update entries:

1. Edit the structured files in `data/`.
2. Run `python3 scripts/validate_data.py`.
3. Run `python3 scripts/generate_readme.py`.
4. Open a Pull Request with the data and generated files together.

Please keep placeholder links such as `https://arxiv.org/abs/` out of `data/`; leave incomplete candidates in `PAPERS_TO_ADD.md` until metadata is complete.

---

## 📬 Contact

If you have questions or suggestions, please open an issue.

---

Last generated on 2026.05.19
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files are not up to date.")
    args = parser.parse_args()

    papers = load_json(ROOT / "data" / "papers.json")
    datasets = load_json(ROOT / "data" / "datasets.json")
    tools = load_json(ROOT / "data" / "tools.json")

    expected_readme = render_readme(papers, datasets, tools)
    expected_timeline = build_timeline_data(papers)
    readme_path = ROOT / "README.md"
    timeline_path = ROOT / "docs" / "timeline_data.json"

    if args.check:
        failures = []
        if readme_path.read_text(encoding="utf-8") != expected_readme:
            failures.append(str(readme_path.relative_to(ROOT)))
        current_timeline = json.loads(timeline_path.read_text(encoding="utf-8"))
        if current_timeline != expected_timeline:
            failures.append(str(timeline_path.relative_to(ROOT)))
        if failures:
            print("Generated files are out of date: " + ", ".join(failures), file=sys.stderr)
            print("Run: python3 scripts/generate_readme.py", file=sys.stderr)
            return 1
        print("Generated files are up to date.")
        return 0

    readme_path.write_text(expected_readme, encoding="utf-8")
    write_json(timeline_path, expected_timeline)
    print("Generated README.md and docs/timeline_data.json.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
